Implementation proposal
wlsf82/tech-interview-sample-project pull request #2
Opened 2021-07-24 22:49 UTC by giselerosa

Implementação da proposta feita na mentoria. 

Com alguns pontos observados: 

- [ ] Remoção de dados sensíveis do log
- [ ] Ajuste no padrão do código 
- [ ] Remoção de dependência de step de test
- [ ] Adoção de commands

2021-07-25 20:18 UTC, wlsf82 commented on cypress.env.json.example
> + "user_mail": "",
Eu normalmente chamo o esse arquivo de `cypress.env.example.json`, pra manter a extensão correta.

E que tal algum exemplo de user e password, já que é um _example file_?

2021-07-25 20:18 UTC, wlsf82 commented on cypress.json
> +    "watchForFileChanges": false
Algum motivo específico para esta mudança?

2021-07-25 20:20 UTC, wlsf82 commented on cypress/integration/crud.spec.js
> +  it('create , edit and delete a note', () => {
Senti falta de poder passar a `note` como parâmetro dos comandos customizados.

Além disso, não acho uma boa prática abstrair as validações, pois tenho que ir para outro arquivo para verificar o que realmente está sendo verificado.

2021-07-25 20:21 UTC, wlsf82 commented on cypress/support/index.js
> +import './login_commands'
Para este projeto, visto que é pequeno, eu deixaria todos os comandos customizados em um único arquivo, por questões de simplicidade.

2021-07-25 20:22 UTC, wlsf82 commented on cypress/support/crud_commands.js
> +
Linha em branco desnecessária.

2021-07-25 20:22 UTC, wlsf82 commented on cypress/support/crud_commands.js
> +
Linha em branco desnecessária.

2021-07-25 20:22 UTC, wlsf82 commented on cypress/support/crud_commands.js
> +
Linha em branco desnecessária.

2021-07-25 20:22 UTC, wlsf82 commented on cypress/support/crud_commands.js
> +
Linha em branco desnecessária.

2021-07-25 20:22 UTC, wlsf82 commented on cypress/support/crud_commands.js
> +
Linha em branco desnecessária.

2021-07-25 20:22 UTC, wlsf82 commented on cypress/support/crud_commands.js
> +
Linha em branco desnecessária.

2021-07-25 20:23 UTC, wlsf82 commented on cypress/support/login_commands.js
> +
Linha em branco desnecessária.

2021-07-25 20:23 UTC, wlsf82 commented on cypress/support/login_commands.js
> +
Linha em branco desnecessária.

2021-07-25 20:23 UTC, wlsf82 requested changes
@giselerosa, acabei de revisar tuas sugestões e deixei algumas observações.
Bom trabalho! 👏🏻

2021-07-25 22:36 UTC, giselerosa commented on cypress.env.json.example
> + "user_mail": "",
Faz sentido o nome do arquino. Vou inserir também um exemplo fictício no example.

2021-07-25 22:38 UTC, giselerosa commented on cypress.json
> +    "watchForFileChanges": false
Sim, coloquei essa configuração para que eu não ficasse reexecutando a cada novo ajuste e save do projeto. Assim, uma vez que eu fechasse todos os pontos que precisava após eu reexecutaria.

2021-07-25 23:08 UTC, wlsf82 commented on cypress.json
> +    "watchForFileChanges": false
Prefiro manter, visto que tal configuração não é relacionada a mudança proposta.

2021-08-05 21:26 UTC, giselerosa commented on cypress/support/index.js
> +import './login_commands'
Faz total sentido.

2021-08-05 21:27 UTC, giselerosa commented on cypress/integration/crud.spec.js
> +  it('create , edit and delete a note', () => {
Faz sentido , fica realmente mais claro e simples de analisar e refatorar

2022-04-22 16:04 UTC, wlsf82 commented
I'm closing it without merging since it was just an exercise.

2022-04-22 16:04 UTC, closed without merging